import jsPDF from 'jspdf';

export interface PayStubData {
  employerName: string;
  employeeName: string;
  employeeSSN: string;
  state: string;
  payPeriodStart: string;
  payPeriodEnd: string;
  payDate: string;
  payType: 'salary' | 'hourly';
  payFrequency: string;
  grossPay: number;
  federalTax: number;
  socialSecurity: number;
  medicare: number;
  stateTax: number;
  netPay: number;
}

function fmt(n: number): string {
  return n.toLocaleString('en-US', { style: 'currency', currency: 'USD' });
}

export function generatePayStubPDF(data: PayStubData): void {
  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'letter' });

  const PRIMARY = [26, 86, 219] as [number, number, number]; // #1a56db
  const DARK = [17, 24, 39] as [number, number, number];     // gray-900
  const GRAY = [107, 114, 128] as [number, number, number];  // gray-500
  const LIGHT = [249, 250, 251] as [number, number, number]; // gray-50
  const WHITE = [255, 255, 255] as [number, number, number];
  const RED = [185, 28, 28] as [number, number, number];     // red-700

  const pageW = 215.9; // letter width mm
  const margin = 20;
  const colRight = pageW - margin;

  // ── Header bar ──
  doc.setFillColor(...PRIMARY);
  doc.rect(0, 0, pageW, 28, 'F');

  doc.setTextColor(...WHITE);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(18);
  doc.text(data.employerName || 'Employer', margin, 12);

  doc.setFontSize(11);
  doc.setFont('helvetica', 'normal');
  doc.text('PAY STUB', colRight, 12, { align: 'right' });

  doc.setFontSize(9);
  doc.text(`Generated by IncomeRecord.com`, colRight, 19, { align: 'right' });

  // ── Pay date line under header ──
  doc.setFillColor(...LIGHT);
  doc.rect(0, 28, pageW, 12, 'F');
  doc.setTextColor(...GRAY);
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9);
  doc.text(`Pay Date: ${data.payDate || 'N/A'}`, margin, 35.5);
  doc.text(`Pay Period: ${data.payPeriodStart || 'N/A'} – ${data.payPeriodEnd || 'N/A'}`, pageW / 2, 35.5, { align: 'center' });
  doc.text(`Frequency: ${data.payFrequency}`, colRight, 35.5, { align: 'right' });

  // ── Employee info section ──
  let y = 50;
  doc.setFillColor(...LIGHT);
  doc.roundedRect(margin, y, pageW - margin * 2, 24, 2, 2, 'F');

  doc.setTextColor(...DARK);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(9);
  doc.text('EMPLOYEE', margin + 5, y + 7);

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(10);
  doc.text(data.employeeName || 'Employee', margin + 5, y + 14);
  doc.setFontSize(8);
  doc.setTextColor(...GRAY);
  const ssnDisplay = data.employeeSSN ? `SSN: ${data.employeeSSN}` : '';
  doc.text(ssnDisplay, margin + 5, y + 20);
  doc.text(`State: ${data.state}`, pageW / 2, y + 14);
  doc.text(`Pay Type: ${data.payType === 'salary' ? 'Salaried' : 'Hourly'}`, pageW / 2, y + 20);

  y += 34;

  // ── Earnings table ──
  const tableW = pageW - margin * 2;

  // Header row
  doc.setFillColor(...PRIMARY);
  doc.roundedRect(margin, y, tableW, 8, 1, 1, 'F');
  doc.setTextColor(...WHITE);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(8);
  doc.text('EARNINGS', margin + 5, y + 5.5);
  doc.text('AMOUNT', colRight - 5, y + 5.5, { align: 'right' });

  y += 8;

  // Earnings row
  doc.setFillColor(...WHITE);
  doc.rect(margin, y, tableW, 8, 'F');
  doc.setTextColor(...DARK);
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9);
  const earningsLabel = data.payType === 'salary' ? 'Salary' : 'Regular/OT Pay';
  doc.text(earningsLabel, margin + 5, y + 5.5);
  doc.text(fmt(data.grossPay), colRight - 5, y + 5.5, { align: 'right' });

  y += 8;

  // Gross pay subtotal
  doc.setFillColor(...LIGHT);
  doc.rect(margin, y, tableW, 9, 'F');
  doc.setFont('helvetica', 'bold');
  doc.text('Gross Pay', margin + 5, y + 6);
  doc.text(fmt(data.grossPay), colRight - 5, y + 6, { align: 'right' });

  y += 19;

  // ── Deductions table ──
  doc.setFillColor(220, 38, 38);
  doc.roundedRect(margin, y, tableW, 8, 1, 1, 'F');
  doc.setTextColor(...WHITE);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(8);
  doc.text('DEDUCTIONS', margin + 5, y + 5.5);
  doc.text('AMOUNT', colRight - 5, y + 5.5, { align: 'right' });

  y += 8;

  const deductions = [
    { label: 'Federal Income Tax (2024 brackets)', value: data.federalTax },
    { label: 'Social Security (6.2%)', value: data.socialSecurity },
    { label: 'Medicare (1.45%)', value: data.medicare },
    { label: `State Income Tax (${data.state})`, value: data.stateTax },
  ];

  deductions.forEach((item, i) => {
    const bg = i % 2 === 0 ? WHITE : LIGHT;
    doc.setFillColor(...bg);
    doc.rect(margin, y, tableW, 8, 'F');
    doc.setTextColor(...DARK);
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(9);
    doc.text(item.label, margin + 5, y + 5.5);
    doc.setTextColor(...RED);
    doc.text(`- ${fmt(item.value)}`, colRight - 5, y + 5.5, { align: 'right' });
    y += 8;
  });

  // Total deductions
  const totalDeductions = data.federalTax + data.socialSecurity + data.medicare + data.stateTax;
  doc.setFillColor(...LIGHT);
  doc.rect(margin, y, tableW, 9, 'F');
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(...DARK);
  doc.text('Total Deductions', margin + 5, y + 6);
  doc.setTextColor(...RED);
  doc.text(`- ${fmt(totalDeductions)}`, colRight - 5, y + 6, { align: 'right' });

  y += 19;

  // ── Net Pay box ──
  doc.setFillColor(...PRIMARY);
  doc.roundedRect(margin, y, tableW, 20, 3, 3, 'F');
  doc.setTextColor(...WHITE);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(14);
  doc.text('NET PAY', margin + 10, y + 13);
  doc.setFontSize(18);
  doc.text(fmt(data.netPay), colRight - 10, y + 13, { align: 'right' });

  y += 32;

  // ── Disclaimer ──
  doc.setTextColor(...GRAY);
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(7);
  const disclaimer =
    'This pay stub is generated for informational purposes only. Estimates use 2024 federal tax brackets ' +
    '(single filer) and state effective rates. Actual withholding may differ. Not tax or legal advice. ' +
    'Generated free at incomerecord.com';
  const lines = doc.splitTextToSize(disclaimer, tableW);
  doc.text(lines, margin, y);

  // ── Footer ──
  doc.setFillColor(...DARK);
  doc.rect(0, 268, pageW, 9, 'F');
  doc.setTextColor(...WHITE);
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(7);
  doc.text('incomerecord.com — Free Pay Stub Generator', pageW / 2, 273.5, { align: 'center' });

  // Save
  const safeName = (data.employeeName || 'employee').split(' ').pop() || 'employee';
  const safeDate = data.payDate || 'pay-stub';
  doc.save(`pay-stub-${safeName.toLowerCase()}-${safeDate}.pdf`);
}
